name: flutter_screen_recording_platform_interface
description: A common platform interface for the flutter_screen_recording plugin
version: 1.0.2
homepage: "https://github.com/Isvisoft/flutter_screen_recording/tree/web/flutter_screen_recording_platform_interface"

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  meta: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
